name: Automated Preprocessing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: true

      - name: Install dependencies
        run: pixi install

      - name: Run preprocessing script
        run: pixi run python ${{ env.PREPROCESS_SCRIPT }}
        env:
          PREPROCESS_SCRIPT: automate_rahmathidayat.py

      - name: Commit and push processed data
        env:
          USERNAME: ${{ secrets.USERNAME }}
          EMAIL: ${{ secrets.EMAIL }}
          DATA_DIR: preprocessing/Graduate_indicators_preprocessing
        run: |
          git config --global user.name "$USERNAME"
          git config --global user.email "$EMAIL"
          git add $DATA_DIR/train_processed.csv $DATA_DIR/test_processed.csv

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m 'Automated: Update preprocessed datasets'
            git push
          fi